version: 2.1

orbs:
  docker: circleci/docker@2.1.0

jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint:latest-debian
    steps:
      - checkout
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile

  test-app:
    docker:
      - image: cimg/go:1.15
    steps:
      - checkout
      - run:
          name: Run tests
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - docker/build:
          image: ghcr.io/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: latest
      - run:
          name: Login to GitHub Container Registry
          command: echo $GITHUB_TOKEN | docker login ghcr.io -u $CIRCLE_PROJECT_USERNAME --password-stdin
      - docker/push:
          image: ghcr.io/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: latest

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs:
          requires:
            - lint-dockerfile
            - test-app
          filters:
            branches:
              only: main

